### ISSUE TITLE
How to fill in the credential of mqtt server?

### ISSUE THREAD

**Issue by Aekung** [opctim/homebridge-espresense#1]
**Describe Your Problem:**

This might be a 2 cent question but I would like to ask if you have the example template for mqtt server that has the authentication enabled. I know it should be filled in options but I'm not sure how to correctly do it.

Thank you in advance.

PS. Have been following this ESPresense Project for quite sometimes but since I don't use HA, I couldn't really try it out at all. Thanks for bringing this to Homebridge Community. I desperately want to try this out since the ESP32 is dirt cheap and if it could do what it's promising with ESPresense, it would be absolutely a game changer to Smart Home industry.

**Logs:**

```
Show the Homebridge logs here, remove any sensitive information.
```

**Plugin Config:**

```json
Show your Homebridge config.json here, remove any sensitive information.
```

**Screenshots:**

**Environment:**

* **Plugin Version**:
* **Homebridge Version**: 
* **Node.js Version**: 
* **NPM Version**: 
* **Operating System**:

**Comment by opctim** [comment]
Hi @Aekung,

this should work according to the regular HTTP URL segmentation:
https://en.wikipedia.org/wiki/URL#Syntax

[Edit]: So for example: mqtt://johndoe:supersafepassword@192.168.1.1:1883

Additionally, you can have a look at the docs of MQTT.js, which is being used under the hood for mqtt communication ( it shares its config options with the ones from homebridge-espresense):
https://github.com/mqttjs/MQTT.js#mqttconnecturl-options

Thank you very much for your appreciation! Feel free to contribute, we still have to implement the UI configuration and add a better documentation!

Best regards

**Comment by Aekung** [comment]
> Hi @Aekung,
> 
> this should work according to the regular HTTP URL segmentation: https://en.wikipedia.org/wiki/URL#Syntax
> 
> [Edit]: So for example: mqtt://johndoe:supersafepassword@192.168.1.1:1883
> 
> Additionally, you can have a look at the docs of MQTT.js, which is being used under the hood for mqtt communication ( it shares its config options with the ones from homebridge-espresense): https://github.com/mqttjs/MQTT.js#mqttconnecturl-options
> 
> Thank you very much for your appreciation! Feel free to contribute, we still have to implement the UI configuration and add a better documentation!
> 
> Best regards

Thank you very much for your reply. I'll try this again tonight and will feedback to you ^^.

Again, thanks for your awesome work!

**Comment by Aekung** [comment]
I can connect to mqtt server just fine now but I can't seem to find any occupancy sensors added by this plugin even after adding the plugin to Homebridge. Homebridge also doesn't show any error log relating to this plugin as well. Do you have any idea what's the problem here?

**Comment by Aekung** [comment]
> I can connect to mqtt server just fine now but I can't seem to find any occupancy sensors added by this plugin even after adding the plugin to Homebridge. Homebridge also doesn't show any error log relating to this plugin as well. Do you have any idea what's the problem here?

The occupy sensor is not appeared in Homekit now. It seems I messed up with the mqtt setting in ESPresense WebUI. I'm now trying to figure out for the easy way to identify my apple devices. Do you have any suggestion on that?

**Comment by opctim** [comment]
Sounds good (I guess you were trying to say that it is working **now**).

Apple Devices are relatively tricky to identify as they are using rolling BLE MACs. Fortunately, ESPresense uses pretty sophisticated fingerprinting techniques. So you should be using the device id, which I found out looks like this for my devices:

- Apple Watch Series 5: apple:1005:9-24
- Apple iPhone 12 Pro: apple:1007:11-8

In general, you should look at the debugging output of your ESPresense device (Serial console) and bring your device close (and keep all other devices away). Like this, you should be able to identify your device id's.

**Comment by Aekung** [comment]
> Sounds good (I guess you were trying to say that it is working **now**).
> 
> Apple Devices are relatively tricky to identify as they are using rolling BLE MACs. Fortunately, ESPresense uses pretty sophisticated fingerprinting techniques. So you should be using the device id, which I found out looks like this for my devices:
> 
> * Apple Watch Series 5: apple:1005:9-24
> * Apple iPhone 12 Pro: apple:1007:11-8
> 
> In general, you should look at the debugging output of your ESPresense device (Serial console) and bring your device close (and keep all other devices away). Like this, you should be able to identify your device id's.

Yes, everything seems to be able to work fine now.

Thanks for the advice. I think I can finally locate my iPhone ID now according to your guidance. 

I do find 1 strange behavior though. All the device id I put in the config file will only show as 1 sensor with the room name. Is it possible if I want each device id to show as separated occupy sensor so I can give it a name of the owner of the device to track whether who is currently in that specific room?

Again, thank you very much for your great work!

**Comment by opctim** [comment]
Unfortunately, that is not possible at the moment as the HomeKit accessories of this plugin are intended to deploy a occupancy sensor per room.

Thank you very much for your feedback!

**Comment by Aekung** [comment]
> Unfortunately, that is not possible at the moment as the HomeKit accessories of this plugin are intended to deploy a occupancy sensor per room.
> 
> Thank you very much for your feedback!

Got it. Thank you for the reply. Hopefully, you would expand the plugin functionality once when you have time =) I can think of a very useful way like having Siri tell my kid that it’s already a bed time if she find her still watching the TV in the living room late at night or something like that.

Anyway, the current state of the plugin is already very useful. Thank you for bring this integration to us Homebridge users ^^

**Comment by Aekung** [comment]
I'm experiencing the occupancy sensor reseting the state back and forth very fast. Says it's occupied for 10 seconds and then reset back to unoccupied and then occupied again within a blink of an eyes. Do you know what could possibly be the problem here or what settings I should tweak to make this goes away? 

I'm now playing with Absorption and Distance but it doesn't seem to work.

Thank you in advance.

**Comment by opctim** [comment]
You can try raising the timeout setting.
